version: 2
jobs:
  build:
    working_directory: /go/src/github.com/seize/go-utils
    docker:
      - image: circleci/golang:1.10
    steps:
      - checkout
      - run:
          name: Dependencies
          command: |
            go get -u github.com/golang/dep/cmd/dep
            dep ensure
            echo "Go dependencies updated"
      - run:
          name: Tests
          command: go test ./... -race -coverprofile=coverage.txt -covermode=atomic
      - run:
          name: Coverage
          command: bash <(curl -s https://codecov.io/bash)
